# Generated by Django 5.1.1 on 2024-09-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_rename_register_date_publisher_established_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='established_date',
            new_name='register_date',
        ),
    ]
